FROM node:20-alpine AS build

WORKDIR /usr/src/app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN set -ex; \
    apk update; \
    apk add --no-cache \
    openssl

COPY . .

RUN npm install && \
  npm run build

RUN DATABASE_URL=${DATABASE_URL} npx prisma@5.18.0 generate

FROM node:20-alpine AS run
RUN set -ex; \
    apk update; \
    apk add --no-cache \
    openssl

RUN mkdir /.npm && chown -R 1001:1001 /.npm

USER 1001:1001
WORKDIR /usr/src/app

COPY --from=build --chown=1001:1001 /usr/src/app/dist ./dist
COPY --from=build --chown=1001:1001 /usr/src/app/node_modules ./node_modules
COPY --from=build --chown=1001:1001 /usr/src/app/package.json ./

ENV NODE_ENV=production
ENV PORT=3010
ENV HOSTNAME="0.0.0.0"

CMD [ "node", "dist/index.js" ]