FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install --production

RUN npm install -g typescript

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3010

ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
