name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          siddjuugi/medium-app:latest
          siddjuugi/medium-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Starting deployment..."
          docker pull siddjuugi/medium-app:latest
          echo "Image pulled successfully"
          docker stop medium-app || true
          docker rm medium-app || true
          echo "Old container stopped and removed"
          docker run -d --name medium-app -p 80:3000 siddjuugi/medium-app:latest
          if [ $? -ne 0 ]; then
            echo "Docker run command failed"
            exit 1
          fi
          echo "New container started"
          docker ps
        echo "Deployment completed"
