name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            siddjuugi/medium-app:latest
            siddjuugi/medium-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Test SSH Connection
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ubuntu@${{ secrets.EC2_HOST }} echo "SSH connection successful"
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
       
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Starting deployment..."
            sudo docker pull siddjuugi/medium-app:latest
            echo "Image pulled successfully"
            sudo docker stop medium-app || true
            sudo docker rm medium-app || true
            echo "Old container stopped and removed"
            sudo docker run -d --name medium-app -p 80:3000  -e DATABASE_URL=${{ secrets.DB_URL}} -e JWT_SECRET=${{ secrets.JWT_SECRET }}  siddjuugi/medium-app:latest
            if [ $? -ne 0 ]; then
              echo "Docker run command failed"
              exit 1
            fi
            echo "New container started"
            docker ps
            echo "Deployment completed"
